### ISSUE TITLE
gzip: /build/i-nex/pkg/i-nex/usr/share/man/man1/i-nex-cpuid.1: No such file or directory

### ISSUE THREAD

**Issue by FadeMind** [eloaders/I-Nex#26]
@eloaders 
See: https://github.com/manjaro/packages-community/pull/215#issuecomment-240958646

**Comment by eloaders** [comment]
Please give me a full log

**Comment by oberon2007** [comment]
This is odd! When I tried a few hours ago, package() failed. See 
[i-nex-7.4.0-6-i686-package.txt](https://github.com/eloaders/I-Nex/files/427634/i-nex-7.4.0-6-i686-package.txt)
When I tried again the package built without issues:
[i-nex_buildlog.txt](https://github.com/eloaders/I-Nex/files/427637/i-nex_buildlog.txt)
So, in essence I have no idea what the problem was in the first place, but the good thing is, it seems, we don't have any problem :laughing:

**Comment by DarkShadow44** [comment]
In case someone comes across this, you can't (always= compile it multithreaded.
You need MAKEFLAGS="-j1", fixed that issue for me.
